server.port=8081
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5433/authdb
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

jwt.secret=${JWT_SECRET:clave-local-de-desarrollo}
jwt.expiration=900000
jwt.refresh-expiration=60480000